branch-defaults:
  cronConfig:
    environment: euglena-dev
  develop:
    environment: euglena-dev
  master:
    environment: euglena-prod
global:
  application_name: tltl-euglena
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
